### ISSUE TITLE
File do not open

### ISSUE THREAD

**Issue by As7500** [premlamsal/awesome-invoice-multi#5]
File didn't contain vendor.php file

**Comment by premlamsal** [comment]
run composer install

**Comment by As7500** [comment]
I have done that too

can you tell me the step what should should I have to run that project I
will re install and install

**Comment by As7500** [comment]
[image: image.png]
how to resolve this

**Comment by As7500** [comment]
tyo tw install bhayo dai 500 error dekhya rakheko xa

[image: image.png]

**Comment by premlamsal** [comment]
Please downgrade the composer.
<img width="892" alt="Screenshot 2023-04-04 at 4 49 22 PM" src="https://user-images.githubusercontent.com/24312128/229772777-00812b7a-85fe-4fcd-acd0-03f3c2d4f815.png">

**Comment by As7500** [comment]
there is not database file that i have to save in my database my sql

**Comment by premlamsal** [comment]
Please, Migrate Database first. Please follow laravel documentation.
